// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0YZKup_FiKCdJ8XlgvtGNQ8KmO1WruNQ',
    appId: '1:326339310794:web:d2c63686d72bd980503033',
    messagingSenderId: '326339310794',
    projectId: 'agroschoolbus',
    authDomain: 'agroschoolbus.firebaseapp.com',
    storageBucket: 'agroschoolbus.firebasestorage.app',
    measurementId: 'G-X3DLSM4CPB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCASBRS3jvotuJCqNJxVNrGaT1i89ZPkec',
    appId: '1:326339310794:android:f2094c896894e906503033',
    messagingSenderId: '326339310794',
    projectId: 'agroschoolbus',
    storageBucket: 'agroschoolbus.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMaE9QZvn7K3qKbkb5JaSGkXI0hMtDDEg',
    appId: '1:326339310794:ios:f561a4545b3c1c57503033',
    messagingSenderId: '326339310794',
    projectId: 'agroschoolbus',
    storageBucket: 'agroschoolbus.firebasestorage.app',
    iosBundleId: 'com.analogue.asbtransporter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMaE9QZvn7K3qKbkb5JaSGkXI0hMtDDEg',
    appId: '1:326339310794:ios:35e3c8fe66d83b7d503033',
    messagingSenderId: '326339310794',
    projectId: 'agroschoolbus',
    storageBucket: 'agroschoolbus.firebasestorage.app',
    iosBundleId: 'com.example.agroschoolbus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0YZKup_FiKCdJ8XlgvtGNQ8KmO1WruNQ',
    appId: '1:326339310794:web:911db315e029c96e503033',
    messagingSenderId: '326339310794',
    projectId: 'agroschoolbus',
    authDomain: 'agroschoolbus.firebaseapp.com',
    storageBucket: 'agroschoolbus.firebasestorage.app',
    measurementId: 'G-7DMENSQ2BV',
  );
}